In [1]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\vidya\anaconda3\envs\data_project\lib\site-packages (2.0.49)
Requirement already satisfied: psycopg2-binary in c:\users\vidya\anaconda3\envs\data_project\lib\site-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in c:\users\vidya\anaconda3\envs\data_project\lib\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\vidya\anaconda3\envs\data_project\lib\site-packages (from sqlalchemy) (4.12.2)

In [2]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine("postgresql://postgres:Vidya%401999@localhost:5432/Olist Brazil")

customers = pd.read_sql("SELECT * FROM Customers", engine)
customers.describe()
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [ ]:
# Repeat Customers 
pd.read_sql("SELECT customer_unique_id, COUNT(DISTINCT order_id) as order_count FROM orders o JOIN customers c ON o.customer_id = c.customer_id GROUP BY customer_unique_id ORDER BY order_count DESC", engine)

                     customer_unique_id  order_count
0      8d50f5eadf50201ccdcedfb9e2ac8455           17
1      3e43e6105506432c953e165fb2acf44c            9
2      1b6c7548a2a1f9037c1fd3ddfed95f33            7
3      6469f99c1f9dfae7733b25662e7f1782            7
4      ca77025e7201e3b30c44b472ff346268            7
...                                 ...          ...
96091  041eaf07c71e1d56b489dff63a270e6a            1
96092  041eb6136ede40c0bd0f31372d7f481e            1
96093  041ecd93f392ac99f53809f2fc47c7fb            1
96094  041fb341560d3bb7036cfab81cfbf063            1
96095  0421cbe19607719626e374b2347686eb            1

[96096 rows x 2 columns]

In [25]:
# Repeat Customers with successful transactions only
pd.read_sql("SELECT customer_unique_id, COUNT(DISTINCT order_id) as order_count FROM orders o JOIN customers c ON o.customer_id = c.customer_id WHERE o.order_status IN ('shipped', 'delivered', 'approved','invoiced','processing') GROUP BY customer_unique_id ORDER BY order_count DESC", engine)

                     customer_unique_id  order_count
0      8d50f5eadf50201ccdcedfb9e2ac8455           16
1      3e43e6105506432c953e165fb2acf44c            9
2      6469f99c1f9dfae7733b25662e7f1782            7
3      1b6c7548a2a1f9037c1fd3ddfed95f33            7
4      ca77025e7201e3b30c44b472ff346268            7
...                                 ...          ...
94981  040dafe8dbcf3251811babf50ae6a0f4            1
94982  040dc1ab0fe089423e1d53a50be09a28            1
94983  040e07d6f99f0d6bee3d272db7dd77ff            1
94984  040e4df45a02c9d398c233227f207f67            1
94985  040f8dcf0a86b8897aaa4eb25e49830f            1

[94986 rows x 2 columns]